Migrate check plugin to 2.0 API, add levels, bump version
elcamlost/checkmk-php-fpm-plugin pull request #15
Opened 2024-08-28 13:32 UTC by moschlar

Supersedes #12

2025-01-03 18:13 UTC, elcamlost requested changes
First of all, please accept my deepest apologies for me ignoring this for so long.
Next, this is a great job done here, thanks a lot for your efforts to improve the plugin.
Could you please take a look into my comments?

2025-01-03 18:13 UTC, elcamlost commented on php-fpm/agents/plugins/php_fpm_pools
> +        listen = section['listen'].strip("'\"")
I didn't get this part. Why should we strip these 3 symbols?
Also this sequence repeats 3 times in this file, so please extract it to the variable and reuse.

2025-01-21 11:10 UTC, moschlar commented on php-fpm/web/plugins/wato/php_fpm_pools.py
> +        ("upper_requests_per_sec",
@jplitza Do you remember your reasoning behind this?

2025-01-21 11:10 UTC, moschlar commented on php-fpm/agents/plugins/php_fpm_pools
> +        listen = section['listen'].strip("'\"")
@jplitza Do you remember your reasoning behind this?

2025-01-21 11:12 UTC, moschlar commented on php-fpm/agents/plugins/php_fpm_pools
> +        listen = section['listen'].strip("'\"")
@elcamlost Basically it's just to support quoted parameters in the config file.

2025-04-25 19:59 UTC, jplitza commented on php-fpm/web/plugins/wato/php_fpm_pools.py
> +        ("upper_requests_per_sec",
I guess my research into conventions yielded a different result. :shrug: 
So nevermind to keep the old name

2025-05-15 17:50 UTC, elcamlost commented
I'm closing it in favor of #18

2025-05-15 17:50 UTC, closed without merging

2025-05-15 17:59 UTC, elcamlost commented
And I've released the new version into checkmk exchange

<img width="960" alt="изображение" src="https://github.com/user-attachments/assets/7fc17102-da10-4d4e-b2d9-5a6c081e8633" />